In [1]:
import numpy as np

In [2]:
np1=np.array([1,2,3,4,5])
print(np1.shape)

(5,)


Multidimentional:

In [3]:
np7= np.full((2,7),7)
print(np7)

[[7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]]


convert list to np:

In [4]:
mlist=[1,2,3,4,5,6]
mnp= np.array(mlist)
print(mnp)
print(mnp[2])

[1 2 3 4 5 6]
3


slicing np arrays?

In [5]:
np10 =np.array([1,2,3,4,5,6,7,8,9])
#1 2 3 4
print(np10[0:4])
#does not inlude val at index 4
#to return till the end [x:]

[1 2 3 4]


In [6]:
np10 =np.array([1,2,3,4,5,6,7,8,9])
#in steps of 2
#1 3 5
print(np10[0:6:2])

[1 3 5]


2-d array?

In [7]:
np20= np.array([[1,2,3],[4,5,6]])
print(np20[0:1, 0:2])
#1 2

[[1 2]]


*Universal functions*
-sqrt
-absolute value
-min\max
-(+),(-) => if +ve-> 1 else if -ve-> -1 , 0->0 (.sign())
-sin() , cos() , log() 
-math operators

In [8]:
np11=np.array([16,25,36])
print(np.sqrt(np11))


[4. 5. 6.]


In [9]:
np12=np.array([1,-2,-3,4,-5])
print(np.abs(np12))

[1 2 3 4 5]


*Copy Vs view* ?
view: whenever u change the original the view changes too (use it when u need the change to be reflected in the copy)(bidirectional)



In [10]:
np2=np.array([1,2,3,4,5])
np3 =np2.view()
print(f'orig np2 {np2}')
print(f'orig np3 {np3}')
#1 2 3 4 5
#1 2 3 4 5
np2[2]=10

print(f'updated np2 {np2}')
print(f'just np3 {np3}')
#1 2 10 4 5
#1 2 10 4 5 


orig np2 [1 2 3 4 5]
orig np3 [1 2 3 4 5]
updated np2 [ 1  2 10  4  5]
just np3 [ 1  2 10  4  5]


In [11]:
np2=np.array([1,2,3,4,5])
np3 =np2.copy()
print(f'orig np2 {np2}')
print(f'orig np3 {np3}')
#1 2 3 4 5
#1 2 3 4 5
np2[2]=10

print(f'updated np2 {np2}')
print(f'just np3 {np3}')
#1 2 10 4 5
#1 2 3 4 5 


orig np2 [1 2 3 4 5]
orig np3 [1 2 3 4 5]
updated np2 [ 1  2 10  4  5]
just np3 [1 2 3 4 5]


*shape and reshape*?

In [12]:

np5=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np5.shape)
#rowes , columns
#(2,5)


(2, 5)


In [13]:
np5=np.array([1,2,3,4,5,6,7,8,9,10])
np6=np5.reshape(2,5)
print(np6)
#1 2 3 4 5
#6 7 8 9 10

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


reshape 3-d ??

In [14]:
np5=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
np7=np5.reshape(2,3,2)
print(np7)
#2 d , 3 rowes , 2 columns


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


*iterating through numpy ?*


In [15]:
tnp1 =np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
for i in tnp1:
    print(i)
#print rowes
    for j in i:
        print(j)
#print columns     

[1 2 3 4 5 6]
1
2
3
4
5
6
[ 7  8  9 10 11 12]
7
8
9
10
11
12


In [16]:
#nditer()? without nested loops
tnp3=np.array([[1,2,3],[4,5,6],[7,8,9]])
for i in np.nditer(tnp3):
    print(i)

1
2
3
4
5
6
7
8
9


**Sorting** np.sort()

In [17]:
#numerical 
snp1=np.array([1,6,7,2,9,0])
print(np.sort(snp1))

#alphapetical
snp2=np.array(['banana','apple','grape','orange'])
print(np.sort(snp2))

#booleans
snp3=np.array([True,False,True,False])
print(np.sort(snp3))


#2D
snp4=np.array([[3,2,1,9],[6,5,4,0]])
print(np.sort(snp4))
#each dimension will be sorted individually



[0 1 2 6 7 9]
['apple' 'banana' 'grape' 'orange']
[False False  True  True]
[[1 2 3 9]
 [0 4 5 6]]


**searching** np.where() 


np.where(condition) -> indices


np.where(condition, do , else) -> new matrix 

In [18]:
snp10=np.array([1,2,3,4,5,2,7,2,9,10])
i=np.where(snp10==2)
print(i)
#the output is a tuple

(array([1, 5, 7]),)


*How to filter numpy array?*

In [20]:
fnp=np.array([1,2,3,4,5])
# make a list of booleans where true -> values u neeed , false -> values u dont need
#to get the even nums
bool_list = [False, True, False, True, False]
print(fnp[bool_list])
#2 4

[2 4]


buuut with filter -> we just but the condition 


In [ ]:
fnp=np.array([1,2,3,4,5])
filtered_l=[]
for i in fnp:
    if i%2==0:
        filtered_l.append(True)
    else:
        filtered_l.append(False)

print(fnp[filtered_l])

#or just :

filtered_l2=fnp%2==0
print (filtered_l2)
print(fnp[filtered_l2])

[2 4]
[False  True False  True False]
[2 4]


*Broadcasting*??
Perform operations on arrays with different shapes


when ?
the dimensions have the same size OR one of them has size of one 

In [24]:
bnp1 =np.array([[1,2,3,4]])
bnp2=np.array([[1],[2],[3],[4]])
print(bnp1.shape)
print(bnp2.shape)
#(1,4)
#(4,1)
print(bnp1*bnp2)
#will work and result in a (4,4) array


(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
