In [1]:
import numpy as np

*p1*

In [2]:
arr=np.zeros((3,3))
arr[np.arange(3),np.arange(3)]=9
print(arr)

[[9. 0. 0.]
 [0. 9. 0.]
 [0. 0. 9.]]


In [3]:
arr = np.zeros((3,3))
arr[np.arange(3),np.arange(2, -1, -1)]=9
print(arr)

[[0. 0. 9.]
 [0. 9. 0.]
 [9. 0. 0.]]



--------------------------------------------------
*p2*

In [66]:
arr1=np.ones((7,7))
arr1[1:-1 , 1:-1]=0
arr1[3,3]=5
print(arr1)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 5. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


---------------------------------------------
*p3*

In [68]:
n= int(input('plz enter n'))
arr2=np.arange(1,n+1) #stop val wont be included
print(arr2)
print()
barr=np.ones((n,1))*arr2
print(barr)

[1 2 3 4 5 6 7]

[[1. 2. 3. 4. 5. 6. 7.]
 [1. 2. 3. 4. 5. 6. 7.]
 [1. 2. 3. 4. 5. 6. 7.]
 [1. 2. 3. 4. 5. 6. 7.]
 [1. 2. 3. 4. 5. 6. 7.]
 [1. 2. 3. 4. 5. 6. 7.]
 [1. 2. 3. 4. 5. 6. 7.]]


-----------------------------------------------
*p4*


In [63]:
r_arr=np.random.randint(1,101,(5,5))
print(r_arr)
print()

M_row=np.max(r_arr,axis=1)
print(f'max in each row: {M_row}')

S_col=np.sum(r_arr,axis=0)
print(f'sum of each column: {S_col}')

m_arr=np.mean(r_arr)
print(f'mean arr {m_arr}')

bool_arr=np.where(r_arr>50, 1, 0)
print(f'bool arr: {bool_arr}')

[[89 23 76 11 93]
 [35 28 38  5 49]
 [99 94 44 88  7]
 [97 18 39 54 24]
 [18 38 23 13 36]]

max in each row: [93 49 99 97 38]
sum of each column: [338 201 220 171 209]
mean arr 45.56
bool arr: [[1 0 1 0 1]
 [0 0 0 0 0]
 [1 1 0 1 0]
 [1 0 0 1 0]
 [0 0 0 0 0]]


--------------------
*p5*

In [ ]:
arr=np.arange(1,31).reshape(6,5)
print(arr)
print()

arr1=arr[2:4 , 0:2]
print(arr1)
print()

arr2=arr[[0,1,2,3],[1,2,3,4]]
print(arr2)

arr3=arr[0:6:2] 
print(arr3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]

[[11 12]
 [16 17]]

[ 2  8 14 20]
[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]


--------------------------
*p6*

In [53]:
scores = np.array([45, 88, 92, 30, 50, 76, 99, 12, 65])
B_passing = scores>=50
print(B_passing)
passing_scores = scores[scores>=50]
print(passing_scores)

perfect_score =np.any (scores==100)
print(perfect_score)

all_pass =np.all (scores>=50)
print(all_pass)
 


[False  True  True False  True  True  True False  True]
[88 92 50 76 99 65]
False
False
